// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DataBase.Entity;

namespace DataBase.Context
{
    public partial class DBAContext : DbContext
    {
        public DBAContext()
        {
        }

        public DBAContext(DbContextOptions<DBAContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Instractor> Instractors { get; set; }
        public virtual DbSet<InstractorSubject> InstractorSubjects { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<QuizMark> QuizMarks { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }

//        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//        {
//            if (!optionsBuilder.IsConfigured)
//            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=ElmotataweraDB;Integrated Security=True");
//            }
//        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Lecture>(entity =>
            {
                entity.HasOne(d => d.Instractor)
                    .WithMany(p => p.Lectures)
                    .HasForeignKey(d => d.InstractorId)
                    .HasConstraintName("FK__Lecture__Instrac__4BAC3F29");

                entity.HasOne(d => d.Room)
                    .WithMany(p => p.Lectures)
                    .HasForeignKey(d => d.RoomId)
                    .HasConstraintName("FK__Lecture__RoomID__48CFD27E");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.Lectures)
                    .HasForeignKey(d => d.SubjectId)
                    .HasConstraintName("FK__Lecture__Subject__49C3F6B7");
            });

            modelBuilder.Entity<QuizMark>(entity =>
            {
                entity.HasOne(d => d.StudentCodeNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.StudentCode)
                    .HasConstraintName("FK__Quiz_Mark__Stude__4CA06362");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasKey(e => e.StuId)
                    .HasName("PK__Student__DD8D498164B53EFD");

                entity.HasOne(d => d.AcademicYear)
                    .WithMany(p => p.Students)
                    .HasForeignKey(d => d.AcademicYearId)
                    .HasConstraintName("FK__Student__Academi__47DBAE45");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}