// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Table("AcademicYear")]
    public partial class AcademicYear : BaseEntity
    {
        public AcademicYear()
        {
            Students = new HashSet<Student>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(50)]
        public string AcademicYearName { get; set; }

        [InverseProperty("AcademicYear")]
        public virtual ICollection<Student> Students { get; set; }
    }
}