// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Keyless]
    [Table("Attendance")]
    public partial class Attendance : BaseEntity
    {
        public int? StudentCode { get; set; }
        public int? LectureCode { get; set; }
        [Column("isAttendance")]
        [StringLength(15)]
        public string IsAttendance { get; set; }
    }
}