// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Table("Instractor")]
    public partial class Instractor: BaseEntity
    {
        public Instractor()
        {
            Lectures = new HashSet<Lecture>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(14)]
        public string NationalId { get; set; }
        [StringLength(50)]
        public string FristName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string ThirdName { get; set; }
        [StringLength(50)]
        public string FouthName { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(200)]
        public string Address { get; set; }
        [StringLength(11)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }

        [InverseProperty("Instractor")]
        public virtual ICollection<Lecture> Lectures { get; set; }
    }
}