// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Keyless]
    [Table("Instractor_Subject")]
    public partial class InstractorSubject: BaseEntity
    {
        public int? SubjectCode { get; set; }
        public int? InstractorCode { get; set; }
    }
}