// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Table("Lecture")]
    public partial class Lecture: BaseEntity
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [Column("RoomID")]
        public int? RoomId { get; set; }
        [Column("SubjectID")]
        public int? SubjectId { get; set; }
        [Column("InstractorID")]
        public int? InstractorId { get; set; }

        [ForeignKey("InstractorId")]
        [InverseProperty("Lectures")]
        public virtual Instractor Instractor { get; set; }
        [ForeignKey("RoomId")]
        [InverseProperty("Lectures")]
        public virtual Room Room { get; set; }
        [ForeignKey("SubjectId")]
        [InverseProperty("Lectures")]
        public virtual Subject Subject { get; set; }
    }
}