// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Keyless]
    [Table("Quiz_Marks")]
    public partial class QuizMark: BaseEntity
    {
        public int? StudentCode { get; set; }
        [StringLength(50)]
        public string Attendance { get; set; }
        [StringLength(10)]
        public string Markes { get; set; }

        [ForeignKey("StudentCode")]
        public virtual Student StudentCodeNavigation { get; set; }
    }
}