// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Table("Room")]
    public partial class Room: BaseEntity
    {
        public Room()
        {
            Lectures = new HashSet<Lecture>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(30)]
        public string Address { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Long { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Lat { get; set; }

        [InverseProperty("Room")]
        public virtual ICollection<Lecture> Lectures { get; set; }
    }
}