// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Table("Student")]
    public partial class Student: BaseEntity
    {
        [Key]
        [Column("Stu_ID")]
        public int StuId { get; set; }
        [StringLength(14)]
        public string NationalId { get; set; }
        [StringLength(50)]
        public string FristName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string ThirdName { get; set; }
        [StringLength(50)]
        public string FouthName { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(200)]
        public string Address { get; set; }
        [StringLength(11)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [Column("AcademicYear_ID")]
        public int? AcademicYearId { get; set; }

        [ForeignKey("AcademicYearId")]
        [InverseProperty("Students")]
        public virtual AcademicYear AcademicYear { get; set; }
    }
}