// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBase.Entity
{
    [Table("Subject")]
    public partial class Subject: BaseEntity
    {
        public Subject()
        {
            Lectures = new HashSet<Lecture>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("Subject")]
        public virtual ICollection<Lecture> Lectures { get; set; }
    }
}